repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.1
    hooks:
      - id: ruff        # lint + format check
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: sh -c 'PYTEST_DISABLE_PLUGIN_AUTOLOAD=1 pytest'  # commande to execute
                                                                #deactivate the auto loading of pytest plug-in
        language: system       # use python interpreter of the venv 
        #deactivate the auto loading of pytest plug-in
        pass_filenames: false  # do not send modified files in parameters
