[smtp]
host = "smtp.gmail.com"
port = 587
user = "qadoc.app.reset@gmail.com"
password = "txyaebrpwkvzzqdi"
from = "Chat RAG <qadoc.app.reset@gmail.com>"
use_tls = true

[app]
base_url = "http://localhost:8501"
